### ISSUE TITLE
findpi leaves terminal in NOECHO mode

### ISSUE THREAD

**Issue by HowardALandman** [jamesacampbell/findpi#18] opened 2020-06-23 17:48 UTC
After a run of (say) `findpi -c 4` completes, the terminal is left in NOECHO mode so you can’t see what you type. This requires running `reset` (while typing blind) to fix, which loses all your shell scrollback. I don’t see any reason why this program needs to go into NOECHO in the first place, but failing to come out of it on exit is definitely user-hostile.

**Comment by james-see** [comment] 2020-06-24 00:17
@HowardALandman interesting, I will have to investigate this, I am assuming this has something to do with spawning a shell for the callback. I will see if I can make sure to clean this up afterwards.

**Comment by james-see** [comment] 2020-06-24 16:10
@HowardALandman this should be fixed now possibly? Please let me know. Version 1.1.4 introduces two dependancies on getmac and psutil but mitigates need to spawn shells for commands. The original project was designed to have no dependancies, which is why I was running all the shell commands, but adding two dependancies that are lightweight seems like a fair tradeoff to not run bare shell commands.

**Comment by james-see** [comment] 2020-06-24 17:28
@HowardALandman I am closing since the subprocess lib has been removed completely from the import. 1.1.5 is the latest please upgrade via pip, speed improvements using a threaded function to enforce timeout on getmac hangs for ip addresses that dont exist. Thanks!

**Closed as completed by james-see** 2020-06-24 17:28 UTC
Labels: bug
